from typing import Protocol


class IObservabilityService(Protocol):
    def observe_vacancy_collected(self, count: int = 1) -> None: ...

    def observe_not_vacancy_detected(self, count: int = 1) -> None: ...

    def observe_skill_match(self, skill: str, count: int = 1) -> None: ...

    def observe_users_registered(self, count: int = 1) -> None: ...

    def observe_users_snapshot(self, total_users: int, active_users: int) -> None: ...
