"""init

Revision ID: cce3ae0cbc82
Revises:
Create Date: 2026-02-27 20:19:36.146504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cce3ae0cbc82"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("specializations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("primary_languages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tech_stack", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("min_experience_months", sa.Integer(), nullable=False),
        sa.Column("mirror_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("mirror_message_id", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("salary_amount", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(), nullable=True),
        sa.Column("work_format", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vacancies_content_hash"), "vacancies", ["content_hash"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vacancies_content_hash"), table_name="vacancies")
    op.drop_table("vacancies")
    # ### end Alembic commands ###
