"""user

Revision ID: e434c0b6ae91
Revises: cce3ae0cbc82
Create Date: 2026-02-28 12:45:53.977665

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e434c0b6ae91"
down_revision: str | Sequence[str] | None = "cce3ae0cbc82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("cv_text", sa.Text(), nullable=True),
        sa.Column("cv_specializations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cv_primary_languages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cv_tech_stack", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cv_experience_months", sa.Integer(), nullable=True),
        sa.Column("filter_experience_min_months", sa.Integer(), nullable=True),
        sa.Column("cv_salary_amount", sa.Integer(), nullable=True),
        sa.Column("cv_salary_currency", sa.String(), nullable=True),
        sa.Column("filter_salary_mode", sa.String(), nullable=False),
        sa.Column("cv_work_format", sa.String(), nullable=True),
        sa.Column("filter_work_format_mode", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("tg_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
