name: Релиз

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Загрузка кода
        uses: actions/checkout@v7

      - name: Установка uv
        uses: astral-sh/setup-uv@v7

      - name: Установка Python
        uses: actions/setup-python@v7
        with:
          python-version-file: .python-version

      - name: Установка зависимостей
        run: uv sync --dev --frozen

      - name: Проверка качества
        run: make quality

      - name: Создание GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
